# Generated by Django 2.2.6 on 2019-11-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_auto_20191113_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default='question'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='answers', to='quizz.Answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.ManyToManyField(related_name='correct_answer', to='quizz.Answer'),
        ),
    ]
