# Generated by Django 2.2.6 on 2019-11-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0004_auto_20191119_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_times',
            field=models.IntegerField(default=0),
        ),
    ]
