# Generated by Django 2.2.6 on 2019-11-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0005_question_correct_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
