# Generated by Django 2.2.6 on 2019-11-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0006_question_question_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_correct_answer', models.IntegerField(default=0)),
                ('number_total_answer', models.IntegerField(default=0)),
                ('player_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_times',
        ),
    ]
